version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws configure list
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Building application...
      - echo Build started on `date`
      - docker build --build-arg BASE_IMAGE=$BASE_IMAGE -t $BUILT_IMAGE:latest .
      - docker tag  $BUILT_IMAGE:latest $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$BUILT_IMAGE:latest
  post_build:
    commands:
      - echo Pushing application to Amazon ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$BUILT_IMAGE:latest
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$BUILT_IMAGE:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
